<?php

declare(strict_types=1);

/**
 * Regenerates src/Pdf/Forms/Appearance/StandardFontMetrics.php — WinAnsi
 * advance widths of the base-14 text fonts, read from the metric-compatible
 * Liberation fonts (Sans = Helvetica, Serif = Times, Mono = Courier).
 *
 * Run: bash scripts/fetch-fonts.sh && php scripts/fixtures/generate-standard-font-metrics.php
 */

require __DIR__.'/../../vendor/autoload.php';

use Dskripchenko\PhpPdf\Font\Ttf\TtfFile;
use Dskripchenko\PhpPdf\Pdf\Forms\Appearance\WinAnsi;

$dir = __DIR__.'/../../.cache/fonts/liberation-fonts-ttf-2.1.5';
$map = [
    'Helvetica' => 'LiberationSans-Regular',
    'Helvetica-Bold' => 'LiberationSans-Bold',
    'Helvetica-Oblique' => 'LiberationSans-Italic',
    'Helvetica-BoldOblique' => 'LiberationSans-BoldItalic',
    'Times-Roman' => 'LiberationSerif-Regular',
    'Times-Bold' => 'LiberationSerif-Bold',
    'Times-Italic' => 'LiberationSerif-Italic',
    'Times-BoldItalic' => 'LiberationSerif-BoldItalic',
];

$rows = [];
foreach ($map as $base14 => $file) {
    $ttf = TtfFile::fromFile("{$dir}/{$file}.ttf");
    $upem = $ttf->unitsPerEm();
    $widths = [];
    for ($code = 32; $code <= 255; $code++) {
        $cp = WinAnsi::codepoint($code);
        $gid = $cp === null ? 0 : $ttf->glyphIdForChar($cp);
        $widths[] = $gid === 0 ? 0 : (int) round($ttf->advanceWidth($gid) * 1000 / $upem);
    }
    $rows[] = sprintf("        '%s' => [%s],", $base14, implode(',', $widths));
}

$body = <<<PHP
<?php

declare(strict_types=1);

namespace Dskripchenko\PhpPdf\Pdf\Forms\Appearance;

/**
 * WinAnsi advance widths (1/1000 em) of the base-14 text fonts, for codes
 * 32..255. Generated by scripts/fixtures/generate-standard-font-metrics.php
 * from the metric-compatible Liberation fonts — do not edit by hand.
 *
 * @internal
 */
final class StandardFontMetrics
{
    private const WIDTHS = [
%s
    ];

    /** Every Courier glyph has the same advance. */
    private const COURIER_WIDTH = 600;

    public static function has(string \$baseFont): bool
    {
        return isset(self::WIDTHS[\$baseFont]) || str_starts_with(\$baseFont, 'Courier');
    }

    /** Advance width of a WinAnsi code, in 1/1000 em. */
    public static function width(string \$baseFont, int \$code): int
    {
        if (str_starts_with(\$baseFont, 'Courier')) {
            return self::COURIER_WIDTH;
        }
        \$table = self::WIDTHS[\$baseFont] ?? self::WIDTHS['Helvetica'];

        return \$code >= 32 && \$code <= 255 ? \$table[\$code - 32] : 0;
    }
}

PHP;

$out = __DIR__.'/../../src/Pdf/Forms/Appearance/StandardFontMetrics.php';
file_put_contents($out, sprintf($body, implode("\n", $rows)));
echo "Wrote {$out}\n";
