<?php

declare(strict_types=1);

/**
 * Generate reference PDF/A documents for external conformance validation.
 *
 * Usage: php scripts/conformance/generate.php [output-dir]
 *
 * Output: one PDF per flavour (pdfa-1b, pdfa-1a, pdfa-2b, pdfa-2u, pdfa-3b),
 * built with embedded Liberation fonts (run scripts/fetch-fonts.sh first)
 * and the vendored sRGB ICC profile. These files are the input for
 * scripts/conformance/verapdf.sh (veraPDF validation in CI).
 */

use Dskripchenko\PhpPdf\Document;
use Dskripchenko\PhpPdf\Element\Cell;
use Dskripchenko\PhpPdf\Element\Heading;
use Dskripchenko\PhpPdf\Element\Paragraph;
use Dskripchenko\PhpPdf\Element\Row;
use Dskripchenko\PhpPdf\Element\Run;
use Dskripchenko\PhpPdf\Element\Table;
use Dskripchenko\PhpPdf\Font\Ttf\TtfFile;
use Dskripchenko\PhpPdf\Layout\Engine;
use Dskripchenko\PhpPdf\Pdf\PdfAConfig;
use Dskripchenko\PhpPdf\Pdf\PdfFont;
use Dskripchenko\PhpPdf\Pdf\PdfXConfig;
use Dskripchenko\PhpPdf\Section;
use Dskripchenko\PhpPdf\Style\RunStyle;

$root = dirname(__DIR__, 2);

require $root.'/vendor/autoload.php';

$fontDir = $root.'/.cache/fonts/liberation-fonts-ttf-2.1.5';
if (! is_readable($fontDir.'/LiberationSans-Regular.ttf')) {
    fwrite(STDERR, "Liberation fonts not cached — run scripts/fetch-fonts.sh first.\n");
    exit(1);
}

$iccPath = $root.'/resources/icc/sRGB2014.icc';
if (! is_readable($iccPath)) {
    fwrite(STDERR, "Missing ICC profile: $iccPath\n");
    exit(1);
}

$outDir = $argv[1] ?? $root.'/build/conformance';
if (! is_dir($outDir) && ! mkdir($outDir, 0777, true)) {
    fwrite(STDERR, "Cannot create output dir: $outDir\n");
    exit(1);
}

$flavours = [
    'pdfa-1b' => [PdfAConfig::PART_1, PdfAConfig::CONFORMANCE_B],
    'pdfa-1a' => [PdfAConfig::PART_1, PdfAConfig::CONFORMANCE_A],
    'pdfa-2b' => [PdfAConfig::PART_2, PdfAConfig::CONFORMANCE_B],
    'pdfa-2u' => [PdfAConfig::PART_2, PdfAConfig::CONFORMANCE_U],
    'pdfa-3b' => [PdfAConfig::PART_3, PdfAConfig::CONFORMANCE_B],
];

$bold = new RunStyle(bold: true);

$section = new Section([
    new Heading(1, [new Run('Conformance Reference Document')]),
    new Paragraph([
        new Run('This document is generated by dskripchenko/php-pdf as a reference '.
            'artifact for automated PDF/A validation with veraPDF. It exercises '.
            'embedded TrueType fonts with subsetting, Cyrillic text, bold runs '.
            'and a table.'),
    ]),
    new Heading(2, [new Run('Multilingual text')]),
    new Paragraph([
        new Run('Архивный формат PDF/A требует встраивания шрифтов и цветового '.
            'профиля. Этот абзац проверяет кириллицу: съешь же ещё этих мягких '.
            'французских булок, да выпей чаю.'),
    ]),
    new Paragraph([
        new Run('Emphasis check: ', $bold),
        new Run('regular text after a bold run, with ligatures — office, floor, '.
            'difficult.'),
    ]),
    new Heading(2, [new Run('Tabular data')]),
    new Table([
        new Row([
            new Cell([new Paragraph([new Run('Flavour', $bold)])]),
            new Cell([new Paragraph([new Run('Standard', $bold)])]),
            new Cell([new Paragraph([new Run('Validator', $bold)])]),
        ]),
        new Row([
            new Cell([new Paragraph([new Run('PDF/A-1b')])]),
            new Cell([new Paragraph([new Run('ISO 19005-1')])]),
            new Cell([new Paragraph([new Run('veraPDF')])]),
        ]),
        new Row([
            new Cell([new Paragraph([new Run('PDF/A-2u')])]),
            new Cell([new Paragraph([new Run('ISO 19005-2')])]),
            new Cell([new Paragraph([new Run('veraPDF')])]),
        ]),
    ]),
]);

$engine = new Engine(
    defaultFont: new PdfFont(TtfFile::fromFile($fontDir.'/LiberationSans-Regular.ttf')),
    boldFont: new PdfFont(TtfFile::fromFile($fontDir.'/LiberationSans-Bold.ttf')),
);

// X-3 and X-4 permit an RGB output intent (sRGB); X-1a mandates CMYK —
// its reference is generated only when the CGATS21 profile is cached
// (scripts/fetch-icc.sh).
$pdfxVariants = [
    'pdfx-3' => PdfXConfig::VARIANT_X3,
    'pdfx-4' => PdfXConfig::VARIANT_X4,
];
$cmykIccPath = $root.'/.cache/icc/CGATS21_CRPC1.icc';
if (! is_readable($cmykIccPath)) {
    fwrite(STDERR, "note: pdfx-1a skipped — run scripts/fetch-icc.sh for the CMYK profile\n");
}

$emit = function (string $name, Document $document) use ($engine, $outDir): bool {
    $path = $outDir.'/'.$name.'.pdf';
    try {
        file_put_contents($path, $document->toBytes($engine));
        echo "generated $path\n";

        return true;
    } catch (\Throwable $e) {
        fwrite(STDERR, "FAILED $name: {$e->getMessage()}\n");

        return false;
    }
};

$failures = 0;
foreach ($flavours as $name => [$part, $conformance]) {
    $ok = $emit($name, new Document(
        $section,
        lang: 'en',
        pdfA: new PdfAConfig(
            $iccPath,
            iccProfileName: 'sRGB2014',
            lang: 'en',
            title: 'php-pdf conformance reference — '.strtoupper($name),
            author: 'dskripchenko/php-pdf',
            part: $part,
            conformance: $conformance,
        ),
    ));
    $failures += $ok ? 0 : 1;
}

foreach ($pdfxVariants as $name => $variant) {
    $ok = $emit($name, new Document(
        $section,
        lang: 'en',
        pdfX: new PdfXConfig(
            $iccPath,
            iccProfileName: 'sRGB2014',
            outputConditionIdentifier: 'sRGB IEC61966-2.1',
            outputCondition: 'sRGB colour space — reference display condition',
            variant: $variant,
            trapped: PdfXConfig::TRAPPED_FALSE,
            title: 'php-pdf conformance reference — '.strtoupper($name),
            author: 'dskripchenko/php-pdf',
        ),
    ));
    $failures += $ok ? 0 : 1;
}

if (is_readable($cmykIccPath)) {
    $ok = $emit('pdfx-1a', new Document(
        $section,
        lang: 'en',
        pdfX: new PdfXConfig(
            $cmykIccPath,
            iccProfileName: 'CGATS21_CRPC1',
            outputConditionIdentifier: 'CGATS21-2-CRPC1',
            outputCondition: 'CGATS 21-2 Reference Print Condition 1',
            registryName: 'http://www.color.org',
            variant: PdfXConfig::VARIANT_X1A,
            trapped: PdfXConfig::TRAPPED_FALSE,
            title: 'php-pdf conformance reference — PDFX-1A',
            author: 'dskripchenko/php-pdf',
        ),
    ));
    $failures += $ok ? 0 : 1;
}

exit($failures > 0 ? 1 : 0);
